"""
PROJECT ID: 604

Title: Check Webiste Status and Restart Docker Containers If Website Is Down

Objective
    Create a Python script that monitors the availability of a website and restarts Docker containers if the website is down. The script should also log the incident details locally.
    The script would run on the same server where the website/docker is running. It would be scheduled to run every X minutes to monitory the site.

Requirements
1. Website Monitoring:
   - The script should make an HTTP GET request to http://demostore.supersqa.com/.
   - It should check the status code and parse the content to verify the page loaded correctly.
   - The script should look for a specific element in the page content to confirm the correct page loaded.

2. Error Handling:
   - If the website is down (i.e., the status code is not 200 or the expected element is not found in the content):
   - Restart the Docker containers my_mysql_container and my_wordpress_container.
    the command to restart container is `docker restart my_mysql_container` and `docker restart my_wordpress_container`
    You just print the command instead of actually executing it.
   - Log the incident details including the timestamp, status code, and the response text.

3. Logging:
   - The script should create a text file with the incident details.
   - The log file should be saved in the same directory where the script exists.
   - Each log file should have a unique name based on the timestamp of the incident.

   

Deliverables
1. Python Script:
   - A Python script that performs the above tasks.
   - The script should use the requests library for making HTTP requests and the subprocess module for restarting Docker containers.

2. Log Files:
    - Sample log files generated by the script.

Notes & Tips:
    - Since the site us up but the script needs to handle it when it is donw, you can simulate a failure by using any random subdomain.
    - The functions to be implemented are provided. But feel free to use your own design. This is just a guide and not requirement to use the function.
      But the provided solution will use the functions outlined here.
"""

import os

# Configuration
url = "http://demostore.supersqa.com/"
#url  = "http://abcdefg.supersqa.com/"  # use to test failure

containers = ["my_mysql_container", "my_wordpress_container"]

log_dir = os.path.dirname(os.path.abspath(__file__))

def check_website():
    """
    Function to check the availability of a website.

    Returns:
        bool: True if the website is up, False otherwise.
        int: The status code of the response.
        str: The response text.
    """
    # <Your code here>
    
def restart_containers():
    """
    Function to restart Docker containers.
    """
    # <Your code here>
        
def log_issue(status_code, text):
    """
    Function to log the incident details.

    Args:
        status_code (int): The status code of the response.
        text (str): The response text.
    """
    # <Your code here>
    
def main():
    """
    Main function to check the website status and restart containers if needed.
    """
    # <Your code here>
    
if __name__ == "__main__":
    main()